blog/urls.py
from django.urls import path,include

from . import views
#http://127.0.0.1/blog
#http://127.0.0.1/blog/1

#http://127.0.0.1:8000
app_name='blog'
urlpatterns = [
    path('',views.blog_list,name='blog_list'),
    path('detail/<int:blog_id>/',views.blog_detail,name='detail'),
    path('type/<int:blog_type>/',views.blog_type,name='blog_type'),
    path('date/<int:year>/<int:month>/',views.blog_date,name='blog_date'),
]

user/urls.py
from django.urls import path,include
from . import views as v
app_name='user'
urlpatterns = [

    path('login/',v.login,name='login'),
    path('login_modal/',v.login_modal,name='login_modal'),
    path('reg/',v.register,name='register'),
    path('user_info/',v.user_info,name='info'),
    path('logout/',v.logout,name='logout'),
    path('change_nickname/',v.change_nickname,name='change_nickname'),
    path('change_password/',v.change_password,name='change_password'),
    path('bind_email/',v.bind_email,name='bind_email'),
    path('send_email/',v.send_email,name='send_email'),
    path('forget_password/',v.forget_password,name='forget_password'),
]

user/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    nickname = models.CharField(max_length=20,verbose_name='昵称')

    def __str__(self):
        return '<Profile:%s> %s'%(self.nickname,self.user.username)


def get_nickname(self):
    if Profile.objects.filter(user=self).exists():
        return Profile.objects.get(user=self).nickname
    else:
        return ''

def get_nickname_or_username(self):
    if Profile.objects.filter(user=self).exists():
        return Profile.objects.get(user=self).nickname
    else:
        return self.username



def has_nickname(self):
    return Profile.objects.filter(user=self).exists()

# 给User类添加新方法
User.get_nickname = get_nickname
User.has_nickname = has_nickname
User.get_nickname_or_username = get_nickname_or_username

user/forms.py
from django import forms
from django.contrib import auth
from django.contrib.auth.models import User
class LoginForm(forms.Form):
    username_or_email = forms.CharField(max_length=20,label='用户名',widget=forms.TextInput(attrs={'class':'form-control','placeholder':'请输入用户名'}))
    password = forms.CharField(max_length=16,label='密码',widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'请输入密码'}))

    def clean(self):
        # cleaned_data = super(LoginForm, self).clean()
        username_or_email = self.cleaned_data.get('username_or_email')
        password = self.cleaned_data.get('password')
        user = auth.authenticate(username=username_or_email,password=password)
        if user is None:
            if User.objects.filter(email=username_or_email).exists():
                username = User.objects.get(email=username_or_email).username
                user = auth.authenticate(username=username,password=password)
                if user:
                    self.cleaned_data['user'] = user
                    return self.cleaned_data
                else:
                    raise forms.ValidationError('用户名或者密码错误')
            else:
                raise forms.ValidationError('用户名或者密码错误')
        else:
            self.cleaned_data['user'] = user
            return self.cleaned_data


class RegForm(forms.Form):
    username = forms.CharField(min_length=3,max_length=10,label='用户名',widget=forms.TextInput(attrs={'class':'form-control','placeholder':'请输入用户名'}))
    password = forms.CharField(min_length=6,max_length=16,label='密码',widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'请输入密码'}))
    password_re = forms.CharField(min_length=6,max_length=16,label='重复密码',widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'重复输入密码'}))
    email = forms.EmailField(label='邮箱',widget=forms.EmailInput(attrs={'class':'form-control','placeholder':'请输入邮箱'}))
    code = forms.CharField(
        label='验证码',
        widget=forms.TextInput(attrs={'class': "form-control", 'placeholder': "请输入验证码"})
    )
    def __init__(self,*args,**kwargs):
        if 'request' in kwargs:
            self.request = kwargs.pop('request')
        super(RegForm, self).__init__(*args,**kwargs)


    def clean_username(self):
        username = self.cleaned_data.get('username')
        user_obj = User.objects.filter(username=username).exists()
        if user_obj:
            raise forms.ValidationError('该用户已经存在')
        else:
            return username
    def clean_email(self):
        email = self.cleaned_data.get('email')
        email_obj = User.objects.filter(email=email).exists()
        if email_obj:
            raise forms.ValidationError('该邮箱已存在')
        else:
            return email
    def clean(self):
        pwd1 = self.cleaned_data.get('password')
        pwd2 = self.cleaned_data.get('password_re')
        if pwd1 != pwd2:
            raise forms.ValidationError('两次输入密码不一致')
        else:
            return self.cleaned_data
    def clean_code(self):
        code = self.cleaned_data.get('code','').strip()
        user_code = self.request.session.get('register','')
        if code == '':
            raise forms.ValidationError('验证码不能为空')
        elif code != user_code:
            raise forms.ValidationError('验证码错误')
        else:
            return code


class ChangeNicknameForm(forms.Form):
    def __init__(self,*args,**kwargs):
        if 'user' in kwargs:
            self.user = kwargs.pop('user')

        super(ChangeNicknameForm, self).__init__(*args,**kwargs)
    nickname_new = forms.CharField(
        label='新的昵称',
        max_length=12,
        widget=forms.TextInput(attrs={'class':'form-control','placeholder':'请输入昵称'})
    )
    def clean(self):
        # 判断用户是否登录
        if self.user.is_authenticated:
            self.cleaned_data['user'] = self.user
        else:
            raise forms.ValidationError('用户未登录！')
    def clean_nickname(self):
        # 判断昵称是否为空
        nickname = self.cleaned_data.get('nickname_new','').strip()
        if nickname == '':
            raise forms.ValidationError('新的昵称不能为空！')
        else:
            return nickname


class BindEmailForm(forms.Form):

    def __init__(self,*args,**kwargs):
        if 'request' in kwargs:
            self.request = kwargs.pop('request')
        super(BindEmailForm, self).__init__(*args,**kwargs)


    email = forms.CharField(
        label='新的邮箱',
        widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': '请输入邮箱'})
    )
    code = forms.CharField(
        label='验证码',
        widget=forms.TextInput(attrs={'class':"form-control",'placeholder':"请输入验证码"})
    )
    def clean(self):
        # 判断用户是否登录
        if self.request.user.is_authenticated:
            self.cleaned_data['user'] = self.request.user
        else:
            raise forms.ValidationError('用户未登录')
        if self.request.user.email !='':
            raise forms.ValidationError('用户邮箱已经绑定')
        return self.cleaned_data


    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('该邮箱已经被绑定')
        else:
            return email

    def clean_code(self):
        code = self.cleaned_data.get('code','').strip()
        user_code = self.request.session.get('bind','')
        if code == '':
            raise forms.ValidationError('验证码不能为空')
        elif code != user_code:
            raise forms.ValidationError('验证码错误')
        else:
            return code


class ChangePassword(forms.Form):


    def __init__(self,*args,**kwargs):
        if 'user' in kwargs:
            self.user = kwargs.pop('user')
        super(ChangePassword, self).__init__(*args,**kwargs)
    old_password = forms.CharField(max_length=16,label='旧密码',widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':"请输入原密码"}))
    password = forms.CharField(max_length=16,label='密码',widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'请输入新密码'}))
    password2 = forms.CharField(max_length=16,label='密码',widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'请再次输入新密码'}))

    def clean(self):
        pwd1 = self.cleaned_data.get('password')
        pwd2 = self.cleaned_data.get('password2')
        if pwd1 != pwd2 or pwd1 =='' or pwd2 == '':
            raise forms.ValidationError('请输入正确新密码')
        return self.cleaned_data

    def clean_old_password(self):
        # 验证旧的密码是否正确
        old_password = self.cleaned_data.get('old_password','')
        if self.user.check_password(old_password):
            return self.cleaned_data
        else:
            raise forms.ValidationError('请输入正确的密码！')

class ForgetPassword(forms.Form):
    def __init__(self,*args,**kwargs):
        if 'request' in kwargs:
            self.request = kwargs.pop('request')
        super(ForgetPassword, self).__init__(*args,**kwargs)


    email = forms.CharField(
        label='您的邮箱',
        widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': '请输入您的邮箱'})
    )

    code = forms.CharField(
        label='验证码',
        widget=forms.TextInput(attrs={'class':"form-control",'placeholder':"请输入验证码"})
    )

    new_password = forms.CharField(
        label='新的密码',
        widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'请输入新密码'})
    )
    def clean_email(self):
        email = self.cleaned_data.get('email')
        if not User.objects.filter(email=email).exists():
            raise forms.ValidationError('此邮箱不存在！')
        else:
            return email

    def clean_code(self):
        code = self.cleaned_data.get('code', '').strip()
        user_code = self.request.session.get('forget', '')
        if code == '':
            raise forms.ValidationError('验证码不能为空')
        elif code != user_code:
            raise forms.ValidationError('验证码错误')
        else:
            return code

user/views.py
import time

from django.shortcuts import render
from django.contrib.auth import authenticate
from django.contrib import auth
from django.http import HttpResponse,JsonResponse
from django.shortcuts import redirect, render,reverse
from .forms import ForgetPassword, LoginForm,RegForm,ChangeNicknameForm,BindEmailForm,ChangePassword
from django.contrib.auth.models import User
from .models import Profile
# Create your views here.
def login(request):
    '''
    username = request.POST.get('username')
    password = request.POST.get('password')
    user = authenticate(request,username=username,password=password)

    referer = request.META.get('HTTP_REFERER',reverse('home'))
    if user:
        auth.login(request,user)
        return redirect(referer)
    else:
        return render(request, 'error.html', {'message': '用户名或者密码不一样'})'''
    if request.method == "POST":
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            users = login_form.cleaned_data.get('user')
            auth.login(request,users)
            url = request.GET.get('path',reverse('home'))
            return redirect(url)
    else:
        login_form = LoginForm()
    context = {}
    context['login_form'] = login_form
    print(login_form.non_field_errors())
    return render(request, 'login.html', context)

def login_modal(request):
    login_form = LoginForm(request.POST)
    data = {}
    if login_form.is_valid():
        user = login_form.cleaned_data.get('user')
        auth.login(request,user)
        data['status'] = 'SUCCESS'
    else:
        data['status'] = 'FAIL'
        data['errmsg'] = '用户名或者密码错误'
    return JsonResponse(data)


def register(request):
    context = {}
    if request.method == 'POST':
        reg_form = RegForm(request.POST,request=request)
        if reg_form.is_valid():
            username = reg_form.cleaned_data.get('username')
            password = reg_form.cleaned_data.get('password')
            email = reg_form.cleaned_data.get('email')
            # 创建用户
            user = User.objects.create_user(username=username, email=email)
            user.set_password(password)
            user.save()
            del request.session['register']
            # 登录用户
            user = auth.authenticate(username=username, password=password)
            auth.login(request, user)
            url = request.GET.get('path',reverse('home'))
            return redirect(url)
    else:
        reg_form = RegForm()
    context['reg_form'] = reg_form
    return render(request, 'register.html', context)


def user_info(request):



    return render(request,'user_info.html')


def logout(request):
    auth.logout(request)

    return redirect(reverse('home'))


def change_nickname(request):
    full_path = request.GET.get('from',reverse('home'))
    if request.method == 'POST':
        form = ChangeNicknameForm(request.POST,user=request.user)
        if form.is_valid():
            nickname = form.cleaned_data.get('nickname_new')
            user = form.cleaned_data.get('user')
            profile,created = Profile.objects.get_or_create(user=user)
            profile.nickname=nickname
            profile.save()
            return redirect(full_path)
    else:

        form = ChangeNicknameForm()
    context = {}
    context['form'] = form
    context['page_title'] = '修改昵称'
    context['form_title'] = '修改昵称'
    context['sub_text'] = '修改'
    context['full_path'] = full_path
    return render(request, 'from.html', context)

def change_password(request):
    full_path = request.GET.get('from',reverse('home'))
    if request.method == 'POST':
        form = ChangePassword(request.POST,user=request.user)
        if form.is_valid():
            new_password = form.cleaned_data.get('password')
            user = request.user
            user.set_password(new_password)
            user.save()
            return redirect(full_path)
    else:
        form = ChangePassword()
    context = {}
    context['form'] = form
    context['page_title'] = '修改密码'
    context['form_title'] = '修改密码'
    context['sub_text'] = '修改'
    context['full_path'] = full_path
    return render(request, 'from.html', context)



def bind_email(request):
    full_path = request.GET.get('from',reverse('home'))
    context = {}
    if request.method == 'POST':
        form = BindEmailForm(request.POST,request=request)
        if form.is_valid():
            email = form.cleaned_data.get('email')
            user = request.user
            print('email=',email)
            user.email = email
            user.save()
            del request.session['bind']

            return redirect(full_path)

    else:
        form = BindEmailForm()
    context['form'] = form
    context['form_title'] = '编辑邮箱'
    context['page_title'] = '编辑邮箱'
    context['sub_text'] = '提交'
    context['full_path'] = full_path
    return render(request,'bind_email.html',context)

def forget_password(request):

    full_path = reverse('home')
    context = {}
    if request.method == 'POST':
        form = ForgetPassword(request.POST, request=request)
        if form.is_valid():
            new_password = form.cleaned_data['new_password']
            email = form.cleaned_data['email']
            print('email=',email)
            user = User.objects.get(email=email)

            user.set_password(new_password)
            user.save()
            del request.session['forget']

            return redirect(full_path)

    else:
        form = ForgetPassword()
    context['form'] = form
    context['form_title'] = '重置密码'
    context['page_title'] = '重置密码'
    context['sub_text'] = '提交'
    context['full_path'] = full_path
    return render(request, 'forget_password.html', context)


# 导入发送邮件的函数
from django.core.mail import send_mail
from django.conf import settings

import random,re

def send_email(request):
    '''
    发送邮件的函数
    :param request:
    :return:
    '''
    data = {}
    email = request.GET.get('email')
    send_for = request.GET.get('send_for','')

    source = 'jnhioj234iojiofnsdmaio32'
    code = ''.join(random.sample(source,4))
    is_email = re.match('.+163\.com',email)
    now = int(time.time())
    send_code_time = request.session.get('now',0)
    if is_email:
        if (now - send_code_time)<30:
            data['status'] = 'error'
        else:
            print(code)
            print(now)
            request.session[send_for] = code
            request.session['now'] = now
            send_mail(
                subject='接受验证码',
                message='<h1>验证码：</h1>%s'%code,
                from_email=settings.EMAIL_FROM,
                recipient_list=[email],
                html_message='<h1>验证码：</h1>%s'%code
            )
            data['status'] = 'SUCCESS'
    else:
        data['status'] = 'error'

    return JsonResponse(data)

user/templates/bind_email.html
{% extends 'from.html' %}



{% block left_btn %}
    <input id="send_email" class="btn btn-primary" type="button" value="获取验证码">
{% endblock %}

{% block script_content %}
    <script type="text/javascript">
        $('#send_email').click(function () {
            var email = $('#id_email').val();
            console.log(email)
            if (email==''){
                $('#tip').text('*邮箱不能为空');
                return false;
            }

            $.ajax({
                url:'/user/send_email/',
                type:'get',
                dataType:'json',
                data:{
                    'email':email,
                    'send_for':'bind'
                },
                cache:false,
                success:function (resp) {
                    if (resp['status']=='error'){
                        alert('错误');
                    }
                    console.log(resp)
                }
            });
            $(this).addClass('disabled');
            $(this).attr('disabled',true);
            var time = 30;
            $(this).text(time+'s');

            var interval = setInterval( ()=> {

                if (time <=0){
                    clearInterval(interval);
                    $(this).removeClass('disabled');
                    $(this).attr('disabled',false);
                    $(this).val('发送验证码');
                    return false;
                }
                time --;
                $(this).val(time+'s')
            },1000)
        })
    </script>

{% endblock %}

user/templates/forget_password.html
{% extends 'from.html' %}



{% block left_btn %}
    <input id="send_email" class="btn btn-primary" type="button" value="获取验证码">
{% endblock %}

{% block script_content %}
    <script type="text/javascript">
        $('#send_email').click(function () {
            var email = $('#id_email').val();
            console.log(email)
            if (email==''){
                $('#tip').text('*邮箱不能为空');
                return false;
            }

            $.ajax({
                url:'/user/send_email/',
                type:'get',
                dataType:'json',
                data:{
                    'email':email,
                    'send_for':'forget'
                },
                cache:false,
                success:function (resp) {
                    if (resp['status']=='error'){
                        alert('错误');
                    }
                    console.log(resp)
                }
            });
            $(this).addClass('disabled');
            $(this).attr('disabled',true);
            var time = 30;
            $(this).text(time+'s');
            var interval = setInterval( ()=> {
                if (time <=0){
                    clearInterval(interval);
                    $(this).removeClass('disabled');
                    $(this).attr('disabled',false);
                    $(this).val('发送验证码');
                    return false;
                }
                time --;
                $(this).val(time+'s')
            },1000)
        })
    </script>

{% endblock %}

user/templates/login.html
{% extends 'base.html' %}

{% block title %}
登录页面
{% endblock %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <div class="container">
            <div class="row">
                <div class="col-xs-4 col-xs-offset-4">
                    <div class="panel panel-default">
                      <div class="panel-heading">
                        <h3 class="panel-title">登录</h3>
                      </div>
                      <div class="panel-body">
                        {% if not user.is_authenticated %}
                            {% for field in login_form %}
                                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                {{ field}}
                                <p class="text-danger">
                                    {{ field.errors.as_text }}
                                </p>
                            {% endfor %}
                                <span class="text-danger pull-left">
                                    {{ login_form.non_field_errors }}
                                </span>
                            <div class="clearfix"></div>
                            <div class="pull-left">
                                <a href="{% url 'user:forget_password' %}">忘记密码</a>
                            </div>
                            <input type="submit" value="登录" class="btn btn-primary pull-right">
                        {% else %}
                            <script type="text/javascript">
                                window.location.href='/'
                            </script>
                        {% endif %}
                      </div>
                    </div>

                </div>
            </div>
        </div>


    </form>
{% endblock %}

user/templates/register.html
{% extends 'base.html' %}

{% block title %}
注册页面
{% endblock %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <div class="container">
            <div class="row">
                <div class="col-xs-4 col-xs-offset-4">
                    <div class="panel panel-default">
                      <div class="panel-heading">
                        <h3 class="panel-title">注册</h3>
                      </div>
                      <div class="panel-body">
                        {% if not user.is_authenticated %}

                            {% for field in reg_form %}
                                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                {{ field}}
                                <p class="text-danger">
                                    {{ field.errors.as_text }}
                                </p>
                            {% endfor %}

                                <span class="text-danger pull-left" id="tip">
                                    {{ reg_form.non_field_errors }}
                                </span>
                            <div class="clearfix"></div>
                            <div class="pull-left">
                                <input id="send_email" class="btn btn-primary" type="button" value="获取验证码">
                            </div>
                            <input type="submit" value="注册" class="btn btn-primary pull-right">
                        {% else %}
                            <script type="text/javascript">
                                window.location.href='/'
                            </script>
                        {% endif %}
                      </div>
                    </div>

                </div>
            </div>
        </div>


    </form>
{% endblock %}
{% block script_content %}

        <script type="text/javascript">
        $('#send_email').click(function () {
            var email = $('#id_email').val();
            console.log(email)
            if (email==''){
                $('#tip').text('*邮箱不能为空');
                return false;
            }

            $.ajax({
                url:'/user/send_email/',
                type:'get',
                dataType:'json',
                data:{
                    'email':email,
                    'send_for':'register'
                },
                cache:false,
                success:function (resp) {
                    if (resp['status']=='error'){
                        alert('错误');
                    }
                    console.log(resp)
                }
            });
            $(this).addClass('disabled');
            $(this).attr('disabled',true);
            var time = 30;
            $(this).text(time+'s');

            var interval = setInterval( ()=> {

                if (time <=0){
                    clearInterval(interval);
                    $(this).removeClass('disabled');
                    $(this).attr('disabled',false);
                    $(this).val('发送验证码');
                    return false;
                }
                time --;
                $(this).val(time+'s')
            },1000)
        })
    </script>

{% endblock %}

user/templates/user_info.html
{% extends 'base.html' %}


{% block title %}
个人资料
{% endblock %}

{% block content %}

<div class="container">
  <div class="row">
    <div class="col-xs-10 col-xs-offset-1">
        <h2>
            {{ user.username }}
        </h2>
        <ul>
            <li>
                昵称：
                {{ user.get_nickname }}
                <a href="{% url 'user:change_nickname'%}?from={{ request.get_full_path }}">点击修改</a>
            </li>
            <li>
                邮箱：
                {% if user.email %}
                    {{ user.email }}
                {% else %}
                    <a href="{% url 'user:bind_email' %}?from={{ request.get_full_path }}">去绑定</a>
                {% endif %}
            </li>
            <li>
                上一次登录的时间：
                {{ user.last_login|date:"Y-m-d H:i:s" }}
            </li>
            <li>
                <a href="{% url 'user:change_password' %}?from={{ request.get_full_path }}">修改密码</a>
            </li>
        </ul>

    </div>
  </div>
</div>
{% endblock %}