blog/urls.py
from django.urls import path,include

from . import views
#http://127.0.0.1/blog
#http://127.0.0.1/blog/1

#http://127.0.0.1:8000
app_name='blog'
urlpatterns = [
    path('',views.blog_list,name='blog_list'),
    path('detail/<int:blog_id>/',views.blog_detail,name='detail'),
    path('type/<int:blog_type>/',views.blog_type,name='blog_type'),
    path('date/<int:year>/<int:month>/',views.blog_date,name='blog_date'),
]

comment/urls.py
from django.urls import path
from . import views
app_name='commit'
urlpatterns =[
    path('update_commit/',views.update_commit,name='update_commit'),

]

likes/urls.py
from django.urls import path
from . import views
app_name='like'
urlpatterns = [
    path('',views.like_num,name='like_change')
]

user/urls.py
from django.urls import path,include
from . import views as v
app_name='user'
urlpatterns = [

    path('login/',v.login,name='login'),
    path('login_modal/',v.login_modal,name='login_modal'),
    path('reg/',v.register,name='register'),
    path('user_info/',v.user_info,name='info'),
    path('logout/',v.logout,name='logout'),
    path('change_nickname/',v.change_nickname,name='change_nickname'),
    path('change_password/',v.change_password,name='change_password'),
    path('bind_email/',v.bind_email,name='bind_email'),
    path('send_email/',v.send_email,name='send_email'),
    path('forget_password/',v.forget_password,name='forget_password'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User,ContentType
# from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
from django.urls import reverse

from read_statistics.models import Read_number,raad_number_Expand,ReadDetailDate
from django.contrib.contenttypes.fields import GenericRelation
# Create your models here.

class BlogType(models.Model):
    # verbose_name=在后台管理的名
    type_name = models.CharField(max_length=15, verbose_name='分类')

    def __str__(self):
        return self.type_name

    def type(self):
        return self.type_name

    # 指定当前方法按照哪个字段进行排序
    type.admin_order_field = 'type_name'
    # 指定方法在后台显示的名称
    type.short_description = '分类'

    def parent(self):
        # 返回父标题的名称
        return self.blog_set.name


class Blog(models.Model,raad_number_Expand):
    title = models.CharField(max_length=30, verbose_name='标题')
    blog_type = models.ForeignKey(BlogType, on_delete=models.CASCADE)
    content = RichTextUploadingField()
    # 设置反向关系
    read_time = GenericRelation(ReadDetailDate)
    author = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    create_time = models.DateTimeField(auto_now_add=True)
    update_time = models.DateTimeField(auto_now=True)

    def get_url(self):
        return reverse('blog:detail', kwargs={'blog_id': self.pk})

    def get_email(self):

        return self.author.email

    def __str__(self):
        return '<Blog:%s>' % self.title


    def type(self):
        return self.blog_type

    # 指定方法在后台显示的名称
    type.short_description = '分类'
    # readnumber.short_description = '阅读数量'
    # 指定字段在后台排序
    type.admin_order_field = 'blog_type'

    class Meta:
        ordering = ['-create_time']

"""
class Read_number(models.Model):
    read_num = models.IntegerField(default=0)
    blog = models.OneToOneField(Blog,on_delete=models.DO_NOTHING)

"""

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.db.models import Sum
from .models import Blog, BlogType
from django.contrib.auth.models import ContentType
from django.core.paginator import Paginator
from django.core.cache import cache
from django.db.models import Count
from user.forms import LoginForm
from read_statistics.utils import get_seven_days_data,read_statistics,today_hot_data,yesterday_hot_data
from django.utils import timezone
import datetime

# Create your views here.
each_page_number = 7
def get_week_hot_data():
    date = timezone.now().date()
    week_time = date-datetime.timedelta(days=7)
    a = Blog.objects.filter(read_time__date__gt=week_time).values('id','title') \
                                                            .annotate(read_nums=Sum('read_time__read_num')) \
                                                            .order_by('-read_nums')
    return a[:5]

def home(request):
    context = {}

    contenttype = ContentType.objects.get_for_model(Blog)
    time,count = get_seven_days_data(contenttype)
    today_hot = today_hot_data(contenttype)
    yesterday_hot = yesterday_hot_data(contenttype)

    week_hot_cache = cache.get('week_hot_datas')
    if week_hot_cache is None:
        week_hot_datas = get_week_hot_data()
        cache.set('week_hot_datas',week_hot_datas,3600)
        week_hot_cache = cache.get('week_hot_datas')

    context['today_hot'] = today_hot
    context['yesterday_hot'] = yesterday_hot
    context['week_hot'] = week_hot_cache
    context['time'] = time
    context['count'] = count

    return render(request, 'home.html',context)


def get_blog_list_data(request,blogs):
    context = {}
    page_num = request.GET.get('page', 1)
    # 获取总共数据paginator对象
    paginator = Paginator(blogs, each_page_number)
    # 获取当前页的数据
    page_of_blogs = paginator.get_page(page_num)
    # 总共页数
    page_ranges = page_of_blogs.paginator.num_pages
    # 当前页
    current_page = page_of_blogs.number

    page_range = [i for i in range(1, page_ranges + 1) if
                  i > current_page - 3 and i < current_page + 3 or i == 1 or i == page_ranges]

    try:
        if page_range[1] != 2:
            page_range.insert(1, '...')
        if page_range[-2] != page_ranges - 1:
            page_range.insert(-1, '...')
    except IndexError:
        pass
    #获取日期归档博客的数量
    dates = Blog.objects.dates('create_time', 'month', order='DESC')#时间对象
    print(dates)
    dic = {}
    for date in dates:

        date_count = Blog.objects.filter(create_time__year=date.year,create_time__month=date.month).count()
        dic[date] = date_count
        print('date=',date)

    context['page_range'] = page_range
    context['blogs'] = page_of_blogs
    context['bolg_types'] = BlogType.objects.annotate(blog_count=Count('blog'))
    context['blog_dates'] = dic
    return context

def blog_list(request):
    blogs = Blog.objects.all()
    context = get_blog_list_data(request,blogs)
    return render(request, 'blog/blog_list.html', context)

def blog_detail(request, blog_id):
    context = {}

    blog = get_object_or_404(Blog, id=blog_id)
    read_cookie_key = read_statistics(request,blog)

    context['previous_page'] = Blog.objects.filter(create_time__gt=blog.create_time).last()
    context['next_page'] = Blog.objects.filter(create_time__lt=blog.create_time).first()
    context['blog'] = blog
    response = render(request,'blog/blog_detail.html',context)
    response.set_cookie(read_cookie_key,'true')


    return response


def blog_type(request, blog_type):

    blog_type = get_object_or_404(BlogType, pk=blog_type)
    blogs = Blog.objects.filter(blog_type=blog_type)
    context = get_blog_list_data(request,blogs)
    return render(request, 'blog/blog_type.html', context)


def blog_date(request,year,month):

    blogs = Blog.objects.filter(create_time__year=year,create_time__month=month)
    context = get_blog_list_data(request,blogs)
    dates = '%d年%d月' % (year,month)
    context['dates'] = dates

    return render(request, 'blog/blog_date.html', context)

blog/templates/blog/blog_date.html
{% extends 'blog/blog_list.html' %}

{% block blog_list_title %}
归档日期:{{ dates }}
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'base.html' %}
{% load static %}
{% load customer %}
{% load like_tags %}
{% block title %}
{{ blog.title }}
{% endblock %}

{% block base_title %}
    <link rel="stylesheet" href="{% static 'blog/blog.css' %}">

    <script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
{% endblock %}

{% block blog_active %}
active
{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-xs-10 col-xs-offset-1">
                <h3>{{ blog.title }}</h3>
                <ul class="blog-info">
                    <li>作者:{{ blog.author }}</li>
                    <li>发表日期:{{ blog.create_time|date:'Y-m-d' }}</li>
                    <li>分类:<a href="{% url 'blog:blog_type' blog.blog_type.pk %}">{{ blog.blog_type }}</a></li>
                    <li>阅读（{{ blog.readnumber }}）</li>
                    <li>评论({% get_comment_count blog %})</li>
                </ul>
                <div class="blog-content">{{ blog.content|safe }}</div>
                <div class="like" onclick="likes(this,'blog',{{ blog.pk }})">
                    <span class="glyphicon glyphicon-thumbs-up {% get_like_status blog %}"></span>
                     <span class="like-num">{% like_nums blog %}</span>
                    <span>点赞</span>
                </div>
                <div class="blog-more">
                    <p>
                        {% if previous_page %}
                            上一页：<a href="{% url 'blog:detail' previous_page.pk %}">{{ previous_page.title }}</a>
                        {% else %}
                            上一页：没有更多了~
                        {% endif %}
                    </p>
                    <p>
                        {% if next_page %}
                            下一页：<a href="{% url 'blog:detail' next_page.pk %}">{{ next_page.title }}</a>
                        {% else %}
                            下一页：没有更多了
                        {% endif %}
                    </p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-10 col-xs-offset-1">
                <div class="comment-area">
                    <h3 class="comment-area-title">这是评论区域</h3>
                    {% if user.is_authenticated %}
                        <form action="{% url 'commit:update_commit' %}" method="post" style="overflow: hidden" id="comment_from">
                            <label for="">{{ user.get_nickname_or_username }},欢迎评论~</label>
                            <div id="reply_content_container" style="display: none">
                                <p id="comment_reply">回复:</p>
                                <div id="reply_content">

                                </div>
                            </div>
                            {% csrf_token %}
                            {% get_comment_form blog as comment_form %}
                            {% for comment in comment_form %}
                                {{ comment }}
                            {% endfor %}
                            <span id="comment_error" class="text-danger pull-left"></span>
                            <input type="submit" class="btn btn btn-primary pull-right" value="评论">
                        </form>
                    {% else %}
                        您还未登录,登录之后方可评论~
                        <a class="btn btn-primary" href="{% url 'user:login' %}?path={{ request.get_full_path }}">登录</a>or
                        <a class="btn btn-danger" href="{% url 'user:register' %}?path={{ request.get_full_path }}">注册</a>

                    {% endif %}
                </div>
                <div class="comment-area">
                    <h3 class="comment-area-title">这是评论展示区</h3>
                    <div id="comment_list">
                        {% get_comment_data blog as comments %}
                        {% for comment in comments %}
                            <div id="root_{{ comment.pk }}" class="comment">
                                <span>{{ comment.user.get_nickname_or_username }}</span>
                                <span>({{ comment.create_time }}):</span>
                                <div id="comment_{{ comment.pk }}">
                                    {{ comment.text|safe }}
                                </div>
                                <div class="like" onclick="likes(this,'{% get_content_type comment %}',{{ comment.pk }})">
                                    <span class="glyphicon glyphicon-thumbs-up {% get_like_status comment %}"></span>
                                     <span class="like-num">{% like_nums comment %}</span>
                                </div>

                                <a href="javascript:reply({{ comment.pk }})">回复</a>
                                {% for reply in comment.root_comment.all %}
                                    <div class="reply">
                                        <span>{{ reply.get_nickname_or_username }}</span>
                                        <span>({{ reply.create_time }})</span>
                                        <span>回复:</span>
                                        <span>{{ reply.user_to.get_nickname_or_username }}</span>
                                        <div id="comment_{{ reply.id }}">
                                            {{ reply.text|safe }}
                                        </div>
                                        <div class="like" onclick="likes(this,'{% get_content_type reply %}',{{ reply.pk }})">
                                            <span class="glyphicon glyphicon-thumbs-up {% get_like_status reply %}"></span>
                                             <span class="like-num">{% like_nums reply %}</span>
                                        </div>
                                        <a href="javascript:reply({{ reply.pk }})">回复</a>
                                    </div>

                                {% endfor %}
                            </div>

                        {% empty %}
                            <p id="none">暂时还没有评论,快来占沙发~</p>
                        {% endfor %}
                    </div>

                </div>
            </div>
        </div>

    </div>
{% endblock %}

{% block script_content %}
    <script type="text/javascript">
        $(document).ready(function () {//页面加载完成后调用
            $('.form-control').focus(function () {//获取登录框焦点事件
                $('.text-danger').html('');
                $(this).val('')
            })
        });
        // 实现python中format方法
        String.prototype.format=function () {//模拟python中的字符串格式化
            var str = this;//arguments:它的值就是传递进来的实参，
            for(var i=0;i<arguments.length;i++){
                // 利用正则匹配到  {i},然后替换    “g”:是全局的意思
                var str = str.replace(new RegExp('\\{'+i+'\\}','g'),arguments[i])
           }
            return str
        };
        function reply(replt_comment_id) {
            console.log('{{ user.is_authenticated }}')
            if ('{{ user.is_authenticated }}'=='False'){

                $('#login_Modal').modal('show');
                $('.modal-backdrop').hide();
                return;

            }
            //实现动态传递评论博客的id值
            $('#reply_comment_id').val(replt_comment_id);
            //将回复的评论内容展示到页面
            var html = $('#comment_'+replt_comment_id).html();
            $('#reply_content').html(html);
            $('#reply_content_container').show();
            //动画效果：点击之后移到评论框
            $('html').animate({scrollTop:$('#comment_from').offset().top - 60},300,function () {
                    CKEDITOR.instances['id_text'].focus()
            })
}

        function timeFormat(timestamp) {//格式化时间
            var datetime = new Date(timestamp * 1000);
            var year = datetime.getFullYear();
            var month = datetime.getMonth()+1;
            var day = datetime.getDay();
            var hour = numFormat(datetime.getHours());
            var minutes = numFormat(datetime.getMinutes());
            var seconds = datetime.getSeconds();
            return year+'年'+month+'月'+day +'日' +'&nbsp;'+ hour+':'+minutes
        }
        function numFormat(num){//将传进的数字截取后面位
            return ('00'+num).substr(-2);
        }
        $('#comment_from').submit(function () {//提交评论触发的函数

            console.log($(this).serialize());
            //判断是否为空
            if (CKEDITOR.instances['id_text'].document.getBody().getText().trim()==''){
                $('#comment_error').text('评论不能为空');
                return false
            }
            //更新数据
            CKEDITOR.instances['id_text'].updateElement();
            //异步提交
            $.ajax({
                url:"{% url 'commit:update_commit' %}",
                type:'post',
                dataType:'json',
                cache:false,
                data:$(this).serialize(),
                success:function (resp) {
                    if (resp['status'] == 'SUCCESS'){
                        //var comment_html = '<div>'+resp['username']+'('+resp['comment_time']+')'+':'+resp['content']+'</div>';
                        if ($('#reply_comment_id').val()=='0'){
                            //插入评论

                            var comment = '<div id="root_{0}" class="comment">'+
                                '<span>{1}</span>'+
                                '<span>({2}):</span>'+
                                '<div id="comment_{0}">{3}</div>'+
                                '<div class="like" onclick="likes(this, \'{4}\', {0})">'+
                                    '<span class="glyphicon glyphicon-thumbs-up"></span>'+
                                     '<span class="like-num">0</span>'+
                                '</div>'+
                                '<a href="javascript:reply({0})">回复</a>'+
                            '</div>';
                            comment = comment.format(resp['pk'],resp['username'],
                                timeFormat(resp['comment_time']),resp['content'],
                                resp['content_type']);
                            $('#comment_list').prepend(comment)

                        }else {
                            //插入回复
                            var html = '<div class="reply">'+
                                        '<span>{0}</span>'+
                                        '<span>({1})</span>'+
                                        '<span>回复:</span>'+
                                        '<span>{2}</span>'+
                                        '<div id="comment_{3}">{4}</div>'+
                                        '<div class="like" onclick="likes(this,\'{5}\',{3})">'+
                                            '<span class="glyphicon glyphicon-thumbs-up"></span>  '+
                                             '<span class="like-num">0</span>'+
                                        '</div>'+
                                        '<a href="javascript:reply({3})">回复</a>'+
                                    '</div>';
                            html = html.format(resp['username'],timeFormat(resp['comment_time']),
                                                    resp['reply_to'],resp['pk'],
                                                        resp['content'],resp['content_type']);
                            $('#root_'+resp['root_pk']).append(html);
                            $('#reply_comment_id').val(0);
                            $('#reply_content_container').hide()
                        }
                        //提交之后将框中的内容变空
                        CKEDITOR.instances["id_text"].setData('');
                        $('#comment_error').html('');
                        $('#none').html('')
                    }
                    else{//请求错错误
                        var message = resp['message'];
                        $('#comment_error').prepend(message)
                    }

                },
                error:function (xhr) {
                    console.log(xhr);
                }
            });
            return false
        });
        function likes(obj,content_type,object_id) {//点赞触发的函数
            var is_active = obj.getElementsByClassName('active').length == 0;
            $.ajax({
                url:'{% url "like:like_change" %}',
                type: 'get',
                data: {
                    content_type:content_type,
                    object_id:object_id,
                    is_active:is_active,
                },
                cache: false,
                success:function (resp) {
                    console.log(resp);
                    if (resp['status']=='SUCCESS') {
                        //更新点赞状态
                        var element = $(obj.getElementsByClassName('glyphicon'));
                        if (is_active) {
                            element.addClass('active')
                        } else {
                            element.removeClass('active')
                        }
                        //更新点赞数量
                        var like_num = $(obj.getElementsByClassName('like-num'));
                        like_num.text(resp['like_num']);
                        return;
                    }
                    if(resp['code']==401){
                        $('#login_Modal').modal('show');
                        $('.modal-backdrop').hide()
                    }else {
                        alert(resp['data'])
                    }
                },
                error:function (xhr) {
                    console.log(xhr)
                }
            })
        }

    </script>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'base.html' %}
{% load static %}
{% load customer %}
{% load like_tags %}
{% block base_title %}
    <link rel="stylesheet" href="{% static 'blog/blog.css' %}">
{% endblock %}

{% block title %}
博客
{% endblock %}
{% block blog_active %}
active
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="clo-xs-12 col-sm-8 col-md-9 col-lg-8">
                <div class="panel panel-default">
                  <div class="panel-heading">{% block blog_list_title %}博客列表（一共有{{ blogs.paginator.count}}篇博客）{% endblock %}</div>
                      <div class="panel-body">
                        {% for blog in blogs.object_list %}
                            <div class="blog">
                                <h3>
                                    <a href="{% url 'blog:detail' blog.pk %}">
                                        {{ blog.title }}
                                    </a>
                                </h3>
                                <p>
                                    <span class="glyphicon glyphicon-tag"></span><a href="{% url 'blog:blog_type' blog.blog_type.pk %}">{{ blog.blog_type }}</a>&nbsp;&nbsp;
                                    <span class="glyphicon glyphicon-time"></span>{{ blog.create_time|date:'Y/m/d' }}&nbsp;&nbsp;
                                    <span>阅读({{ blog.readnumber }}）</span> &nbsp;&nbsp;
                                    <span>评论({% get_comment_count blog %})</span>
                                    <span>点赞({% like_nums blog %})</span>
                                </p>
                                {% if blog.content|length > 10 %}
                                    <p>{{ blog.content|striptags|slice:':30' }}...</p>
                                {% else %}
                                    <p>{{ blog.content }}</p>
                                {% endif %}
                            </div>
                        {% empty %}
                            <div class="blog">
                                 <h3>暂时还没有博客</h3>
                            </div>
                        {% endfor %}
                      </div>
                </div>
                {# 分页器 #}
                <div class="page">
                    <ul class="pagination">
                    {# 上一页 #}
                        {% if blogs.has_previous %}
                            <li>
                              <a href="?page={{ blogs.previous_page_number }}" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                              </a>
                            </li>
                        {% else %}
                            <li><a href="javascript: void (0)">&laquo;</a></li>
                        {% endif %}
                    {# 中间页码 #}
                        {% for blog in page_range %}
                            {% if blog == blogs.number %}
                                <li class="active"><a href="">{{ blog }}</a></li>
                            {% elif blog == '...' %}
                                <li><a href="javascript: void (0)">{{ blog }}</a></li>
                            {% else %}
                                <li><a href="?page={{ blog }}">{{ blog }}</a></li>
                            {% endif %}
                         {% endfor %}
                    {# 下一页 #}
                        {% if blogs.has_next %}
                            <li>
                              <a href="?page={{ blogs.next_page_number }}" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                              </a>
                            </li>
                        {% else %}
                            <li class="disabled"><a href="javascript:void (0)">&raquo;</a></li>
                        {% endif %}
                    </ul>
                    <p>
                        共有{{ blogs.paginator.count }}篇博客，当前第{{ blogs.number }}页,共{{ blogs.paginator.num_pages }}页
                    </p>
                </div>
            </div>
            <div class="hidden-xs col-sm-4 col-md-3 col-lg-4">
                <div class="panel panel-default">
                  <div class="panel-heading">博客分类</div>
                      <div class="panel-body">
                        <ul class="blog_types">
                           {% for bolg_type in bolg_types %}
                                <li><a href="{% url 'blog:blog_type' bolg_type.pk %}">{{ bolg_type }}（{{ bolg_type.blog_count }})</a></li>
                            {% endfor %}
                        </ul>
                      </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">归档日期</div>
                    <div class="panel-body">
                        <ul>
                            {% for date,count in blog_dates.items %}
                                <li><a href="{% url 'blog:blog_date' date.year date.month %}">{{ date.year }}年{{ date.month }}月（{{ count }})</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

blog/templates/blog/blog_type.html
{% extends 'blog/blog_list.html' %}
{% block title %}
{{ blog_type.type_name }}
{% endblock %}

{% block blog_list_title %}
    <h3>分类：{{ blog_type.type_name }}</h3>一共有（{{ blogs.paginator.count }}）篇博客

{% endblock %}