blog/urls.py
from django.urls import path,include

from . import views
#http://127.0.0.1/blog
#http://127.0.0.1/blog/1

#http://127.0.0.1:8000
app_name='blog'
urlpatterns = [
    path('',views.blog_list,name='blog_list'),
    path('detail/<int:blog_id>/',views.blog_detail,name='detail'),
    path('type/<int:blog_type>/',views.blog_type,name='blog_type'),
    path('date/<int:year>/<int:month>/',views.blog_date,name='blog_date'),
]

user/urls.py
from django.urls import path,include
from . import views as v
app_name='user'
urlpatterns = [

    path('login/',v.login,name='login'),
    path('login_modal/',v.login_modal,name='login_modal'),
    path('reg/',v.register,name='register'),
    path('user_info/',v.user_info,name='info'),
    path('logout/',v.logout,name='logout'),
    path('change_nickname/',v.change_nickname,name='change_nickname'),
    path('change_password/',v.change_password,name='change_password'),
    path('bind_email/',v.bind_email,name='bind_email'),
    path('send_email/',v.send_email,name='send_email'),
    path('forget_password/',v.forget_password,name='forget_password'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min(1).js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- 最新版本的 Bootstrap 核心 CSS 文件 -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% block base_title %}

    {% endblock %}
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="">个人博客网站</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="{% block home_active %}{% endblock %}"><a href="{% url 'home' %}">首页</a></li>
                    <li class="{% block blog_active %}{% endblock %}"><a href="{% url 'blog:blog_list' %}">博客</a></li>
                </ul>
                {% if user.is_authenticated %}
                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            {% if user.has_nickname %}
                              {{ user }} ({{ user.get_nickname }})
                            {% else %}
                                {{ user }}
                            {% endif %}

                              <span class="caret"></span>
                          </a>
                          <ul class="dropdown-menu">
                            <li><a href="{% url 'user:info' %}">个人资料</a></li>
                              {% if user.is_staff or user.is_superuser %}
                                <li><a href="/admin">后台管理</a></li>
                              {% endif %}
                            <li role="separator" class="divider"></li>
                            <li><a href="{% url 'user:change_password' %}">修改密码</a></li>
                            <li><a href="{% url 'user:logout' %}">退出登录</a></li>
                          </ul>
                        </li>
                    </ul>
                {% else %}
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="{% url 'user:login' %}?path={{ request.get_full_path }}">登录</a></li>
                        <li><a href="{% url 'user:register' %}?path={{ request.get_full_path }}">注册</a></li>
                    </ul>
                {% endif %}

            </div>

        </div>

    </div>

    {% block content %}

    {% endblock %}
            <!-- Modal -->
        <div class="modal fade" id="login_Modal" tabindex="-1" role="dialog">
            <div class="modal-dialog modal-sm" role="document">
                <form action="" id="login_modal">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title">登录</h4>
                        </div>
                        <div class="modal-body">
                            {% csrf_token %}
                            {% for field in form %}
                                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                {{ field}}
                            {% endfor %}
                            <p class="text-danger"></p>
                        </div>
                        <div class="modal-footer">
                            <button type="submit" class="btn btn-primary">登录</button>
                            <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    <script type="text/javascript">
        $('#login_modal').submit(function () {//模态框登录触发的函数
            $.ajax({
                url:'{% url "user:login_modal" %}',
                type:'post',
                cache:false,
                data:$(this).serialize(),
                success:function (resp) {
                    if(resp['status']=='SUCCESS'){
                        window.location.reload()//让当前窗口进行刷新
                    }else if(resp['status']=='FAIL'){
                        $('.text-danger').html(resp['errmsg'])
                    }else {
                        alert('错误.....')
                    }
                }
            });
            return false;
        })

    </script>
    {% block script_content %}

    {% endblock %}
</body>
</html>

templates/error.html
{% extends 'base.html' %}

{% block base_title %}
错误
{% endblock %}
{% block content %}
{{ message }}
{% endblock %}

templates/from.html
{% extends 'base.html' %}

{% block title %}
{{ page_title }}
{% endblock %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <div class="container">
            <div class="row">
                <div class="col-xs-4 col-xs-offset-4">
                    <div class="panel panel-default">
                      <div class="panel-heading">
                        <h3 class="panel-title">{{ form_title }}</h3>
                      </div>
                      <div class="panel-body">
                            {% for field in form %}
                                {% if not form.is_hedden %}
                                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                    {{ field}}
                                {% endif %}

                                <p class="text-danger">
                                    {{ field.errors.as_text }}
                                </p>
                            {% endfor %}
                                <span id="tip" class="text-danger pull-left">
                                    {{ login_form.non_field_errors }}
                                </span>
                            <div class="clearfix"></div>
                            <div class="pull-left">
                                {% block left_btn %}

                                {% endblock %}
                            </div>
                            <div class="pull-right">
                                <input type="submit" value="{{ sub_text }}" class="btn btn-primary">
                                <input class="btn btn-default" type="button" value="返回" onclick="window.location.href='{{ full_path }}'">
                            </div>
                      </div>
                    </div>

                </div>
            </div>
        </div>


    </form>
{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
首页
{% endblock %}
{% block base_title %}
    <link rel="stylesheet" href="{% static '/css/home.css' %}">
    <script src="http://cdn.highcharts.com.cn/highcharts/highcharts.js"></script>

{% endblock %}
{% block home_active %}
active
{% endblock %}
{% block content %}
<h1>欢迎来到我的博客!开发中...</h1>

        <!-- 图表容器 DOM -->
    <div id="container"></div>
    <h3>今日热门博客</h3>
    <ul>
        {% for todays in today_hot %}
            <li><a href="{% url 'blog:detail' todays.content_object.id %}">{{ todays.content_object.title }}</a>({{ todays.read_num }})</li>
        {% empty %}
            <li>今天没有热门博客</li>
        {% endfor %}

    </ul>
    <h3>昨天热门博客</h3>
    <ul>
        {% for yester in yesterday_hot %}
            <li><a href="{% url 'blog:detail' yester.content_object.id %}">{{ yester.content_object.title }}</a>({{ yester.read_num }})</li>
        {% empty %}
            <li>昨天没有热门博客</li>
        {% endfor %}
    </ul>
    <h3>本周热门博客</h3>
    <ul>
        {% for week in week_hot %}
            <li><a href="{% url 'blog:detail' week.id %}">{{ week.title }}</a>({{ week.read_nums }})</li>
        {% endfor %}

    </ul>
    <!-- 引入 highcharts.js -->
    <script src="http://cdn.highcharts.com.cn/highcharts/highcharts.js"></script>
    <script>
        // 图表配置
        var options = {
            chart: {
                type: 'line'                          //指定图表的类型，默认是折线图（line）
            },
            title: {
                text: null               // 标题
            },
            xAxis: {
                title: { text:'前7日阅读统计' },
                categories: {{ time|safe }},  // x 轴分类
                {#tickmarkPlacement:'on'#}
            },
            yAxis: {
                title: { text: null },                // y 轴标题
                labels:{ enabled:false },      //y轴1.2.3.4.5

            },
            series: [{                              // 数据列
                name: '阅读量',                        // 数据列名
                data: {{ count }}                     // 数据
            }],
            plotOptions: {
                line: {
                    dataLabels: {
                        enabled: true
                    }
                }
            },
            legend: { enabled: false },         //版权信息隐藏
            credits:{ enabled: false}       //图例隐藏

        };
        // 图表初始化函数
        var chart = Highcharts.chart('container', options);
    </script>
{% endblock %}